### ISSUE TITLE
Add edge node for usecase1

### ISSUE THREAD

**Issue by jabrena** [jabrena/101-docker#68]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/147263/203419334-0b9be364-4cd6-48ba-aaa2-de4ffa6b28d6.png">

- https://cloud.spring.io/spring-cloud-gateway/reference/html/

**Comment by jabrena** [comment]
-  https://srvaroa.github.io/kubernetes/eureka/paas/microservices/loadbalancing/2020/02/12/eureka-kubernetes.html

**Comment by jabrena** [comment]
- https://github.com/sagaramelmatti/spring-boot-microservices-docker-compose

**Comment by jabrena** [comment]
Configuration example:

```yml
spring:
  application:
    name: api-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: bank-microservice
          uri: http://bank-microservice:9001/
          predicates:
            - Path=/banks/**
        - id: customer-microservice
          uri: http://customer-microservice:9002/
          predicates:
            - Path=/customers/**
```
