### ISSUE TITLE
Review options to not touch code and change Server port by external configuration

### ISSUE THREAD

**Issue by jabrena** [jabrena/101-docker#79]
- https://www.baeldung.com/spring-boot-change-port
- https://stackoverflow.com/questions/21083170/how-to-configure-port-for-a-spring-boot-application
- https://stackoverflow.com/questions/46057625/externalising-spring-boot-properties-when-deploying-to-docker
- https://stackoverflow.com/questions/72013795/how-does-spring-boot-application-yml-port-server-port-work
- https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.files.property-placeholders
- https://stackoverflow.com/questions/21083170/how-to-configure-port-for-a-spring-boot-application/47223314

**Example:**

```yml
app:
  image: my-app:latest
  ports:
    - "8080:8080"
  environment:
     SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/table
```

**Comment by jabrena** [comment]
```
  usecase1ag:
    image: ghcr.io/jabrena/usecase1-api-gateway:buildpacks-native.0.0.1-SNAPSHOT
    ports:
      - 9192:9192
    environment:
      - SERVER_PORT=9192
      - USE_CASE_A=http://usecase1a:8084/
      - USE_CASE_AN=http://usecase1an:7084/
    depends_on:
      - "usecase1an"
    networks:
      - usecase1
  usecase1a:
    image: ghcr.io/jabrena/usecase1-a:buildpacks-jvm.0.0.1-SNAPSHOT
    ports:
      - 8084:8084
    environment:
      - SERVER_PORT=8084
      - USE_CASE_B=http://usecase1b:8081/
    depends_on:
      - "usecase1b"
    networks:
      - usecase1
    profiles:
      - donotstart
```
