### ISSUE TITLE
Find an easy way to disable "non essentials" Docker compose services for testing purposes in local

### ISSUE THREAD

**Issue by jabrena** [jabrena/101-docker#81]
- https://stackoverflow.com/questions/37254881/is-there-any-way-to-disable-a-service-in-docker-compose-yml

**Comment by jabrena** [comment]
```
  usecase1a:
    image: ghcr.io/jabrena/usecase1-a:buildpacks-jvm.0.0.1-SNAPSHOT
    ports:
      - 8084:8084
    environment:
      - SERVER_PORT=8084
      - USE_CASE_B=http://usecase1b:8081/
    depends_on:
      - "usecase1b"
    networks:
      - usecase1
    profiles:
      - donotstart
```
